#include <stdio.h>
int main()
{
  int a, b, c, d, aux;
  printf("Operadores de asignación\n");
  printf("+=\n"); // a=a+b;
  printf("Inserte 1er núm: ");
  scanf("%d", &a);
  printf("Inserte valor de acumulación: ");
  scanf("%d", &b);
  a+=b;
  printf("Primera iteración: %d\n", a);
  a+=b;
  printf("Segunda iteración: %d\n", a);
  a+=b;
  printf("Tercera iteración: %d\n", a);
  printf("-=\n"); // a=a-b;
  printf("Inserte 1er núm: ");
  scanf("%d", &a);
  printf("Inserte valor de acumulación: ");
  scanf("%d", &b);
  a-=b;
  printf("Primera iteración: %d\n", a);
  a-=b;
  printf("Segunda iteración: %d\n", a);
  a-=b;
  printf("Tercera iteración: %d\n", a);
  printf("*=\n"); // a=a*b;
  printf("Inserte 1er núm: ");
  scanf("%d", &a);
  printf("Inserte valor de acumulación: ");
  scanf("%d", &b);
  a*=b;
  printf("Primera iteración: %d\n", a);
  a*=b;
  printf("Segunda iteración: %d\n", a);
  a*=b;
  printf("Tercera iteración: %d\n", a);
  printf("/=\n"); // a=a/b;
  printf("Inserte 1er núm: ");
  scanf("%d", &a);
  printf("Inserte valor de acumulación: ");
  scanf("%d", &b);
  a/=b;
  printf("Primera iteración: %d\n", a);
  a/=b;
  printf("Segunda iteración: %d\n", a);
  a/=b;
  printf("Tercera iteración: %d\n", a);
  printf("%=\n"); // a=a%b;
  printf("Inserte 1er núm: ");
  scanf("%d", &a);
  printf("Inserte valor de acumulación: ");
  scanf("%d", &b);
  a%=b;
  printf("Primera iteración: %d\n", a);
  a%=b;
  printf("Segunda iteración: %d\n", a);
  a%=b;
  printf("Tercera iteración: %d\n", a);
  printf("Operadores monarios\n");
  printf("Preincremento\n"); // a=a+1;
  printf("Valor: ");
  scanf("%d", &a);
  ++a;
  printf("Primera iteración: %d\n", a);
  ++a;
  printf("Segunda iteración: %d\n", a);
  b= ++a + ++a;
  printf("Suma: %d y valor actual: %d\n", b, a);
  printf("Posincremento\n"); // a=a+1;
  printf("Valor: ");
  scanf("%d", &a);
  a++;
  printf("Primera iteración: %d\n", a);
  a++;
  printf("Segunda iteración: %d\n", a);
  b= a++ + a++;
  printf("Suma: %d y valor actual: %d\n", b, a);
  printf("Predecremento\n"); // a=a-1;
  printf("Valor: ");
  scanf("%d", &a);
  --a;
  printf("Primera iteración: %d\n", a);
  --a;
  printf("Segunda iteración: %d\n", a);
  b= --a + --a;
  printf("Suma: %d y valor actual: %d\n", b, a);
  printf("Posdecremento\n"); // a=a-1;
  printf("Valor: ");
  scanf("%d", &a);
  a--;
  printf("Primera iteración: %d\n", a);
  a--;
  printf("Segunda iteración: %d\n", a);
  b= a-- + a--;
  printf("Suma: %d y valor actual: %d\n", b, a);

}
